### PR TITLE
move test, update requirements

### PR DESCRIPTION
**Pull request by evelynmitchell**
The test was in the wrong directory:
Moved it to the correct tests location.

```
____________ ERROR collecting zeta/nn/modules/test_dense_connect.py ____________
ImportError while importing test module '/usr/src/zeta/zeta/nn/modules/test_dense_connect.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
zeta/__init__.py:1: in <module>
    from zeta.utils.disable_logging import disable_warnings_and_logs
zeta/utils/__init__.py:10: in <module>
    from zeta.utils.disable_logging import disable_warnings_and_logs
zeta/utils/disable_logging.py:5: in <module>
    import numexpr as ne
E   ModuleNotFoundError: No module named 'numexpr'
```

### CODE REVIEW

**Comment by evelynmitchell** [comment]
Added numexpr to requirements.  Tests now running.

**Comment by evelynmitchell** [comment]
One of the tokenizer tests depended on writing a file. Removed it.

**Comment by evelynmitchell** [comment]
Removed test to fix #77

**Comment by evelynmitchell** [comment]
model/base.py did not raise NotImplemented here, The test was looking for that.

**Comment by evelynmitchell** [comment]
Fixing  tests

**Review by kyegomez — CHANGES_REQUESTED** [review]
Remove the base model changes it's supposed to stay as it is

**Comment by evelynmitchell** [comment]
The base model test checks for Not Implemented. If it stays as is, then the test should be removed.

**Comment by kyegomez** [comment]
@evelynmitchell then have them removed so i can accept

**Comment by evelynmitchell** [comment]
Dine

**Pull request merged**
